- name: Install MariaDB server
  ansible.builtin.apt:
    name: mariadb-server
    state: present
    update_cache: true

- name: Ensure MariaDB is started
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Create user for HAProxy health-check
  community.mysql.mysql_user:
    name: haproxy
    host: localhost
    state: present
